### ISSUE TITLE
"Unexpected token" error when running on < Node 12

### ISSUE THREAD

**Issue by Minneth** [adyen-examples/adyen-react-online-payments#82]
Seems there might be an issue running this on anything < node12 which is contrary to the docs that state Node v8.

I've cloned the repo and I've installed the packages as well as created the environment variables file with my own details, but when I run "npm run dev" I'm getting "SyntaxError: Unexpected token ;"

Originally tested using Node 10, but as soon as I switch to Node 12 everything works.

Here's the full log:

adyen-react-online-payments % npm run start

> adyen-react-online-payments@0.1.0 start /Users/martincrawley/Documents/Code/adyen-react-online-payments
> dotenv -e .env react-scripts start

/Users/martincrawley/Documents/Code/adyen-react-online-payments/node_modules/eslint-webpack-plugin/node_modules/jest-worker/build/index.js:110
  _ending;
         ^

SyntaxError: Unexpected token ;
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Users/martincrawley/Documents/Code/adyen-react-online-payments/node_modules/eslint-webpack-plugin/dist/getESLint.js:9:5)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! adyen-react-online-payments@0.1.0 start: `dotenv -e .env react-scripts start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the adyen-react-online-payments@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/martincrawley/.npm/_logs/2022-09-26T17_13_48_300Z-debug.log

**Comment by gcatanese** [comment]
Thanks @Minneth for pointing this out. I have verified and the [Adyen Node SDK](https://github.com/Adyen/adyen-node-api-library) requires Node 12 or higher. The Github actions also are configured accordingly.

I think the README file has a mistake and needs to be updated (ie support Node 12+). Let me know if you need help/support with Node 10 specificallly.
